### ISSUE TITLE
createResource第二个参数建议传递route.getServiceId()或 route.getLocation()

### ISSUE THREAD

**Issue by xwsg** [SpringCloud/sample-zuul-swagger2#1]
当采用如下配置时，若
```yml
zuul:
  routes:
    client-a-api:  # <-- 这里不等于serviceId 
      path: /client/**
      serviceId: client-a
```
`createResource(route.getServiceId(), route.getId(), "2.0")` 中 `route.getId()` 默认取到的是`Map<String, ZuulRoute>`的key，也就是这里的`client-a-api`，swagger api docs 路径则解析为： `/client-a-api/v2/api-docs`，是无法正常访问的。

建议 `route.getId()`改为 `route.getServiceId()`或 `route.getLocation()`
